### ISSUE TITLE
lmfao

### ISSUE THREAD

**Issue by Supelion** [mangoess/AcaiTools#1]
lmfao

**Comment by Supelion** [comment]
also, its k, I hate taking down projects that people work on even if they didn't get my permission

**Comment by mangoess** [comment]
Very sorry, Do I have permission to use your idea?

**Comment by Supelion** [comment]
yeah its k, you can lmao

**Comment by Supelion** [comment]
idk how to close this pls do it for me

**Comment by Supelion** [comment]
oh nvm I see the button
